project:
  type: website
  output-dir: docs

website:
  title: "NM-Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd

format:
  html:
    theme: 
      -nickstyles.scss
    mainfont: Montserrat
    toc: true



