---
title: "My Master's Application Blog"
---

This Blog is about my purpose for pursuing my Master's of Public Heath with an emphasis in Industrial Hygiene

Industrial Hygiene:

\"...that science and art devoted to the anticipation, recognition,
evaluation, and control of those environmental factors or stresses
arising in or from the workplace, which may cause sickness,
impaired health and well-being, or significant discomfort among
workers or among the citizens of the community.\" (OSHA)

# Statement of Purpose

My father introduced me to the field of Environmental and Occupational Health & Safety and has had a career in this industry my entire life. Naturally, I took an interest in what he did every day and frequently asked questions. While in high school, I was afforded the opportunity to work in my father's firm during my summer breaks, and I was enrolled in private industry EPA and CA/OSHA accredited courses that are part of State and Federal accreditation to perform the type of work that included environmental and occupational surveys and evaluation for hazards such as asbestos, lead, and construction safety. The courses I took were: • EPA AHERA -- 40hr Asbestos Contractor Supervisor Competent Person Course • EPA AHERA -- 3-day Building Inspector Course for Asbestos • EPA / CA CDPH -- 40hr Lead Risk Assessor and Inspector Course • OSHA 30 -- Construction Safety Course I am also currently pursuing the California Site Surveillance Technician accreditation, to add to my abilities in this field. These studies and experiences gave me an exciting opportunity to work and collaborate with other folks in professional settings that included a combination of field and office environments where every day would be similar but distinctly different. Furthermore, it presented me with the challenges of combining human interaction with the environmental and regulatory processes required by the job. As a UC Santa Barbara freshman, I was very excited to be a part of the Environmental Studies program, with an eye toward eventually pursuing a Graduate degree in Public Health. I typically enjoyed the science courses since they provided a better understanding of the analytical processes involved in air, water, and soils sampling common to the various types of projects I participated in. I was also inspired by courses in Green Building and Waste Management. During my time at UCSB, I have always looked at the material to see how I could relate it to the Industrial Hygiene work I had experience in. I'm sure this was natural given my work experience, but it continually reminded me how interested I am in this field where I have only scratched the surface. Given my experience and background, I believe that pursuing a Master's in Public Health is a natural progression. I look forward to applying to the program with the intent of focusing on Industrial Hygiene and Occupational Health and Safety. Ultimately, I plan to use this educational opportunity to become a Certified Industrial Hygienist and make my career in the industrial hygiene field. I think I can positively impact the health of the people I work with in the future by obtaining this education and certification.
